In [1]:
import sys
sys.path.insert(0, '..')
import numpy as np
import qutip as qt
import src
from src import (utils, paulialg, stabilizer, circuit)

# Link to QuTip Library

Pauli operators can be easily converted to the `Qobj` in qutip library
- `Pauli.to_qupit()`
- `PauliList.to_qutip()`
- `PauliMonomial.to_qutip()`
- `PauliPolynomial.to_qutip()`

In [2]:
paulialg.pauli('XY').to_qutip()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
Qobj data =
[[0.+0.j 0.+0.j 0.+0.j 0.-1.j]
 [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
 [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
 [0.+1.j 0.+0.j 0.+0.j 0.+0.j]]

In [3]:
paulialg.paulis('XY','ZZ').to_qutip()

[Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[0.+0.j 0.+0.j 0.+0.j 0.-1.j]
  [0.+0.j 0.+0.j 0.+1.j 0.+0.j]
  [0.+0.j 0.-1.j 0.+0.j 0.+0.j]
  [0.+1.j 0.+0.j 0.+0.j 0.+0.j]],
 Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = True
 Qobj data =
 [[ 1.  0.  0.  0.]
  [ 0. -1.  0.  0.]
  [ 0.  0. -1.  0.]
  [ 0.  0.  0.  1.]]]

In [4]:
((2+3j)*paulialg.pauli('XY')).to_qutip()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 0.+0.j  0.+0.j  0.+0.j  3.-2.j]
 [ 0.+0.j  0.+0.j -3.+2.j  0.+0.j]
 [ 0.+0.j  3.-2.j  0.+0.j  0.+0.j]
 [-3.+2.j  0.+0.j  0.+0.j  0.+0.j]]

In [5]:
((2+3j)*paulialg.pauli('XY')+(1.5)*paulialg.pauli('ZZ')).to_qutip()

Quantum object: dims = [[2, 2], [2, 2]], shape = (4, 4), type = oper, isherm = False
Qobj data =
[[ 1.5+0.j  0. +0.j  0. +0.j  3. -2.j]
 [ 0. +0.j -1.5+0.j -3. +2.j  0. +0.j]
 [ 0. +0.j  3. -2.j -1.5+0.j  0. +0.j]
 [-3. +2.j  0. +0.j  0. +0.j  1.5+0.j]]